#!/usr/bin/env bash
# setup-domain.sh — one-command domain onboarding for MFlow (BT-Apache, name-based vhost + reverse proxy)
# Usage: bash setup-domain.sh mflow.yourdomain.com
set -euo pipefail
DOMAIN="${1:-}"
[[ -z "$DOMAIN" ]] && { echo "Usage: bash $0 mflow.yourdomain.com"; exit 1; }
[[ $DOMAIN != *.* ]] && { echo "Needs a full domain like mflow.yourdomain.com"; exit 1; }

VHOST_DIR=/www/server/panel/vhost/apache
mkdir -p "$VHOST_DIR" /var/www/mflow/run/logs

cat > "$VHOST_DIR/mflow-domain.conf" <<EOF
# MFlow domain vhost — generated by setup-domain.sh on $(date +%F)
# HTTP reverse proxy to console :8088. Add TLS after issuing a cert (see docs/domain-setup.md).
<VirtualHost *:80>
    ServerName $DOMAIN
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / http://127.0.0.1:8088/
    ProxyPassReverse / http://127.0.0.1:8088/
    ErrorLog /var/www/mflow/run/logs/domain-error.log
    CustomLog /var/www/mflow/run/logs/domain-access.log combined
</VirtualHost>
EOF

# ensure proxy modules are loaded (BT Apache usually has them; uncomment if present)
CONF=/www/server/apache/conf/httpd.conf
for mod in proxy_module proxy_http_module; do
  if grep -qE "^#.*${mod}" "$CONF" && ! grep -qE "^LoadModule ${mod}" "$CONF"; then
    sed -i "s|#\(.*${mod}/mod_.*\)|\1|" "$CONF" && echo "enabled $mod"
  fi
done

/www/server/apache/bin/apachectl configtest
/www/server/apache/bin/apachectl -k graceful

echo ""
echo "✅ $DOMAIN → MFlow 工作台 反代已配置（HTTP）"
echo "下一步："
echo "  1. 确认 DNS A 记录 $DOMAIN → 172.96.253.73 已生效"
echo "  2. 浏览器访问 http://$DOMAIN"
echo "  3. HTTPS 证书：按 docs/domain-setup.md 第 3 步（宝塔面板或 acme.sh）"
